### ISSUE TITLE
Add static mode where bboxes cannot be modified or deleted

### ISSUE THREAD

**Issue by ffeldhaus** [gereleth/jupyter-bbox-widget#1]
To display the annotation output of a service it would be very useful to have a static mode where bboxes cannot be modified or deleted.

**Comment by gereleth** [comment]
It's hilarious how I spend time making things interactive and the first request is to turn it all off. :joy:

Anyway, this seemed easy enough to do. In v0.3.0 you can set `widget.view_only = True` to disable interactions with bboxes. Set back to `False` to enable them again.

**Comment by ffeldhaus** [comment]
Thank you very much, you're doing a great job. Are the bboxes still selectable in view only mode? I think that's the one interactivity which would still be useful, e.g. to display relevant for information about that specific bbox (e.g. in case of OCR you can display the text).

**Comment by gereleth** [comment]
Yes, you can still select a bbox by clicking on it and switch between bboxes with `Tab` / `Shift-Tab`.
