### ISSUE TITLE
No image showing

### ISSUE THREAD

**Issue by radford1** [gereleth/jupyter-bbox-widget#10]
Is there a way to debug why an image isn't showing? I'm trying to use the Databricks file store and am able to view a http url of the image from this github example folder.
Not able to see
![Screen Shot 2022-08-16 at 10 35 21 AM](https://user-images.githubusercontent.com/25943444/184920253-9163128b-8f32-408a-a473-c087fd395cc6.png)
.
Able to ls the file on the file system
![Screen Shot 2022-08-16 at 10 35 27 AM](https://user-images.githubusercontent.com/25943444/184920435-4ef2c529-8376-4ab6-b2c6-accddac34f6c.png)

**Comment by gereleth** [comment]
If the image isn't showing using a local file path you can try encoding it as a base64 string. Something along these lines (I copied this over from [`examples/introduction.ipynb`](https://github.com/gereleth/jupyter-bbox-widget/blob/main/examples/introduction.ipynb)).

```python
from jupyter_bbox_widget import BBoxWidget
import base64

def encode_image(filepath):
    with open(filepath, 'rb') as f:
        image_bytes = f.read()
    encoded = str(base64.b64encode(image_bytes), 'utf-8')
    return "data:image/jpg;base64,"+encoded
    
widget = BBoxWidget(
    image = encode_image('/dbfs/FileStore/fruit.jpg'),
    classes = ['apple', 'orange', 'pear'],
)
```

**Comment by gereleth** [comment]
Hi @radford1,
Did this help with your problem?

**Comment by aicarras** [comment]
Hi @gereleth. I was facing a similar issue to @radford1, but your suggested solution fixed it for me. Thanks!

**Comment by gereleth** [comment]
Hi @aicarras, thanks for confirming!

Maybe I should make this tip more prominent somewhere =).

**Comment by quillaur** [comment]
Thx @gereleth , I had this issue with google colab and your trick fixed it nicely !

**Comment by GeorgePearse** [comment]
Hey, thanks a lot for an excellent tool. I also hit the this and this snippet fixed it. Had no idea what to try before that though.

**Comment by pvilas** [comment]
Hi, this solved my google collab issue too!

**Comment by gereleth** [comment]
In version 0.6.0 this should no longer be necessary as the widget will now read in the image file and send its contents to be displayed in the UI.
