### ISSUE TITLE
No widget is shown

### ISSUE THREAD

**Issue by hritam-98** [gereleth/jupyter-bbox-widget#14]
Hi, I am following the instructions on my jupyter notebook but nothing is shown:

![image](https://user-images.githubusercontent.com/51586842/217498703-6829e8e6-4374-4243-8006-2b390c9085fc.png)

I have installed the required packages as follows:

!pip install jupyter_bbox_widget ipywidgets
!pip install --upgrade jupyter_core jupyter_client
!pip install jupyter_contrib_nbextensions
!pip install --upgrade ipympl --user
!jupyter nbextension enable --py widgetsnbextension

Am I missing something?

**Comment by gereleth** [comment]
Do regular `ipywidgets` work in this setup? A Button or an IntSlider for example? If not then that's something to figure out first.
Can you see the widget in the Binder demo?

I'm afraid I can't really do remote debugging to figure this out. Try installing things into a fresh virtual env. Maybe try to restart the jupyter server, the kernel, clear cell outputs, force refresh page. Check the browser console for error messages.
