### ISSUE TITLE
Set new keybindings and eddit layout

### ISSUE THREAD

**Issue by FishingBehindTheNet** [gereleth/jupyter-bbox-widget#17]
Im working on an AI assisted labeling tool whitch works around this library. I saw that you have made keybindings for the buttons in the widget and I was wondering if its posble for me to add my owne ore eddit the ones you made? I looked ad the code but i did not grasp how it works. 

Another question(les important): is there a way to add buttons next to the skip and submit? my current selution is to put them above the witget and merge them with the box function of ipwidgets but it would be grat to be able to add them to the side of them.

**Comment by gereleth** [comment]
Hi there!

If you want your own set of buttons you can create the widget with `hide_buttons=True` and make whatever buttons you need with `ipywidgets`.

The key events currently work like this:

- js side keyboard event processing is defined in [/src/BBoxWidget.svelte#L136](https://github.com/gereleth/jupyter-bbox-widget/blob/d94d0f1238fea90eb7ebc9cbdfbe7ab0d393f463/src/BBoxWidget.svelte#L136). Depending on which key is pressed it edits the bboxes or sends skip/submit messages to the python side.
- python side handles skip/submit messages in [jupyter_bbox_widget/bbox.py#L87](https://github.com/gereleth/jupyter-bbox-widget/blob/d94d0f1238fea90eb7ebc9cbdfbe7ab0d393f463/jupyter_bbox_widget/bbox.py#L87).

I don't really think I can handle adding a mechanism for defining arbitrary buttons and/or keyboard shortcuts. Maybe [`ipyevents`](https://github.com/mwcraig/ipyevents) could help with the keyboard events? Or fork and edit the two places I mentioned above =).

I know of another library that uses this widget for AI-assisted labeling: [`pylabel`](https://github.com/pylabel-project/pylabel). I haven't really looked past their readme but maybe it's worth checking out.
