### ISSUE TITLE
bbox close icon not displayed correctly

### ISSUE THREAD

**Issue by ffeldhaus** [gereleth/jupyter-bbox-widget#2]
It seems there is an encoding issue with the character of the close icon. You can see the issue in the code here where only a 🗙 character is shown.

https://github.com/gereleth/jupyter-bbox-widget/blob/fc817e37d4bda599080d8c94e375c6d6ea99f7b2/src/BBox.svelte#L173

Here is a screenshot of the issue:
![image](https://user-images.githubusercontent.com/910802/131528011-e2aa8a67-d845-403e-90ca-f07457680ab0.png)

**Comment by gereleth** [comment]
Looks like the unicode icon is not as general as I hoped).
I see an 'x' icon in your message and in the code:

![изображение](https://user-images.githubusercontent.com/6080076/131541753-20e5c243-1621-4b82-8e3d-679ef1d65315.png)

I'll take a look at drawing it with svg lines I guess.

**Comment by ffeldhaus** [comment]
That made me really curious. It seems this is a Mac OS X problem with their default font not rendering U+1F5D9 (CANCELLATION X) which you are using and which is from Unicode 7.0. I would suggest to switch to a character supported on Mac OS X like ✖ - U+2716 (Heavy Multiplication X).

**Comment by gereleth** [comment]
I decided to go with svg lines to avoid any future unicode drama with symbols not displaying correctly. 
Should be fixed in v0.3.2.
