### ISSUE TITLE
Multilabel conversion

### ISSUE THREAD

**Issue by gurkirt** [gereleth/jupyter-bbox-widget#21]
What do I need to change to make it support multiple labels on top of the bounding box e.g labels = [car, red, SUV], or labels = [Truck, black, pickup] or labels = [apple, green] etc? 

Where do I need to make changes to support multiple labels? I am happy to send PR.

thank you for the tool and guidance.

**Comment by gereleth** [comment]
You could leverage attached widgets for this I think. If you need more properties recorded for every bbox then create some widgets for editing them and attach to the bbox widget. Like this:

```python
from jupyter_bbox_widget import BBoxWidget
import ipywidgets as widgets

bbox_widget = BBoxWidget(
    image='fruit.jpg',
    classes=['apple', 'orange', 'pear'],
)
color_widget = widgets.ToggleButtons(description='color',options=['red','orange','yellow','green'])
size_widget = widgets.ToggleButtons(description='size', options=[1,2,3])

bbox_widget.attach(color_widget, 'color')
bbox_widget.attach(size_widget, 'size')

container = widgets.VBox([
    bbox_widget,
    color_widget,
    size_widget
])

container
```

The attached widgets will then let you edit additional properties of every bbox:

![image](https://github.com/gereleth/jupyter-bbox-widget/assets/6080076/bb127f86-a7bd-4e8d-b629-369d519b3242)

The bboxes property looks like this now, note the color and size properties recorded.

```
[{'x': 42,
  'y': 174,
  'width': 228,
  'height': 191,
  'label': 'pear',
  'color': 'yellow',
  'size': 2}]
  ```
  
  You're not limited to toggle buttons, use any ipywidgets that make sense in your particular case.

**Comment by gurkirt** [comment]
Sounds great! Thank you so much!
