### ISSUE TITLE
Modifying the coordinates

### ISSUE THREAD

**Issue by sulaimanvesal** [gereleth/jupyter-bbox-widget#22]
Hi,

I get the bbx coordinates from user, but I refine the bbxes and I want to plot again the refined version.

The following code update the dict for widget.bboxes, but when I call the widget again, it shows the older coordinates.

Is there away to update the coordinates?

```Python
for i, prediction in enumerate(pboxes):
    x1, y1, x2, y2 = prediction
    width = x2 - x1
    height = y2 - y1
    
    # Update the existing dictionary in widget_bboxes with the new coordinates
    widget.bboxes[i]['x'] = x1
    widget.bboxes[i]['y'] = y1
    widget.bboxes[i]['width'] = width
    widget.bboxes[i]['height'] = height
```

**Comment by sulaimanvesal** [comment]
If this does not work, I want to append the the refined bbx coordinates in the widget, and when I call the widget should show the older and the new bboxes. I could add this also to dict, but state of widget doesn't change.

**Comment by gereleth** [comment]
Editing bboxes in place doesn't sync them with js side. The way around this is to copy bboxes into a new list of new dicts, modify it in your loop and then assign to `widget.bboxes`. Then you should see the changes reflected in the UI.

Something like this: 

```python
bboxes = [{**bbox} for bbox in widget.bboxes]

for i, prediction in enumerate(pboxes):
    x1, y1, x2, y2 = prediction
    width = x2 - x1
    height = y2 - y1
    
    # Update the existing dictionary in widget_bboxes with the new coordinates
    bboxes[i]['x'] = x1
    bboxes[i]['y'] = y1
    bboxes[i]['width'] = width
    bboxes[i]['height'] = height

widget.bboxes = bboxes
```
