### ISSUE TITLE
FEATURE REQUEST- Image pairs for anki cards

### ISSUE THREAD

**Issue by bbc18** [gereleth/jupyter-bbox-widget#23]
Dear gereleth,

I was looking at your code to try to adapt it to create anki flashcards (apps.ankiweb.net) from uploaded images in a Google Colab. I sort of manage in Python, however I have no idea of JS and was unable to tweak your code.

In short, what is needed is the ability to have “matched pairs” of annotations of two classes “front of card” and “back of card” as “front_01” + “back_01”, “front_02” + “back _02”, etc…

Therefore, I believe the main change would be:
1)	Add an automatic counter (for each class) that is incremented automatically after each annotation of that class. The counter could be saved either as the annotation name, or the as an additional property.
2)	Ideally, this counter should be shown on the image, alongside the class label.
3)	Ideally, the user should be able to set a value for this counter in case of annotations snafus.
With this, I could crop the image pairs and create the anki cards with python in an Colab Workbook.

If you have time, could you please try to implement the following features in order to make it possible. 
Thank you very much,
bbc

P.S. This repository: github.com/robxcalib3r/Image2Anki has a video of a similar feature, except that it works in local (his program also does other things such as OCR).

**Comment by gereleth** [comment]
Hi, bbc =).

I'm going to suggest a way to achieve your desired process without js modifications.

I'm not familiar with anki flashcards and I don't know if anki is capable of showing bbox annotations (but I guess it's not). So maybe you need to modify the uploaded file to turn it into front/back images - maybe crop to selected portions or maybe draw a box and save that as a new image. This can be done python side - given a source image and a bbox you can make the modification and save that as a new file.

So you could use "Front" and "Back" as classes and press Submit when you have annotated a front/back pair. Put your logic for creating front/back images into the function that runs on submit. It's going to have access to current bboxes so you can use python to do the cropping/saving. You can then rename the labels of processed pairs to "front_{i}" and "back_{i}" (or just clear them to reduce visual clutter).

Here's some starter code with this workflow:

```python
from jupyter_bbox_widget import BBoxWidget

widget = BBoxWidget(
    image='fruit/fruit.jpg',
    classes=['_', 'Front', 'Back'],
)

counter = 0

@widget.on_submit
def on_submit():
    global counter
    counter += 1
    # get front and back bboxes
    front = next(bbox for bbox in widget.bboxes if bbox['label']=='Front')
    back = next(bbox for bbox in widget.bboxes if bbox['label']=='Back')
    # do the cropping/saving here
    
    # rename labels adding counter
    new_bboxes = []
    for bbox in widget.bboxes:
        new_bbox = {**bbox}
        if new_bbox['label'] in ('Front', 'Back'):
            new_bbox['label'] += f'_{counter}'
        new_bboxes.append(new_bbox)
    widget.bboxes = new_bboxes
    # or maybe just clear them instead?
    
# display the widget
widget
```

"Front_{i}" and "Back_{i}" bboxes are going to have the default blue color, so I included an empty class to make current Front/Back annotations visually distinct. This is how it looks after two submits:

![image](https://github.com/gereleth/jupyter-bbox-widget/assets/6080076/8c5e0177-28db-4361-a368-d715d99112df)

I hope this helps =).
