### ISSUE TITLE
the possibility to directly feed the numpy/PIL image instead of the filename

### ISSUE THREAD

**Issue by ashesh-0** [gereleth/jupyter-bbox-widget#26]
I work with microscopy data where data is stored with different formats. It will help if there is a possibility of just passing in the image data one wants to annotate instead of having to pass the filepath.

**Comment by gereleth** [comment]
You can pass base64-encoded image data instead of the filename. For a simple jpg image you could do something like this:

```python
from jupyter_bbox_widget import BBoxWidget
import base64

def encode_image(filepath):
    with open(filepath, 'rb') as f:
        image_bytes = f.read()
    encoded = str(base64.b64encode(image_bytes), 'utf-8')
    return "data:image/jpg;base64,"+encoded
    
widget = BBoxWidget(
    image=encode_image('fruit/fruit.jpg'),
    classes=['apple', 'orange', 'pear'],
)
```

It's probably possible to adapt this approach to microscopy data - read in the image, convert it to some format the browser would understand and show it with base64 encoding.

**Comment by gereleth** [comment]
Since version 0.6.0 we can also use binary image data without additional base64 encoding. So if you have a PIL image you can save it into an in-memory buffer and give that to `widget.image_bytes`.

```python
from io import BytesIO

bytes_io = BytesIO()
image.save(bytes_io, format='jpeg')
widget.image_bytes = bytes_io.getvalue()
```
