### ISSUE TITLE
Save image in bboxes

### ISSUE THREAD

**Issue by MarcSkovMadsen** [gereleth/jupyter-bbox-widget#27]
If you `skip` and annotate multiple images, then you do not know which image the annotation is from.

Please also save the `image` string in the `bboxes` value.

You might make it a boolean option to include the `image` in the `bboxes` value.

**Comment by MarcSkovMadsen** [comment]
## Workaround

Inspired by the `.attach` implementation, I see I can use the private method `_set_bbox_property` using the `.selected_image` and `.image`.

I.e. I can get

![image](https://github.com/user-attachments/assets/6e5fd706-0a5c-4d19-a31e-5fb24a81767c)

**Comment by gereleth** [comment]
Well all the required data is already present in the widget, it's up to you to record it in a way that preserves the image-bboxes connection. If you want annotations as a flat list of dicts then the submit function could have something like this:

```python
# init
annotations = []
# in submit fn
annotations.extend({'image': widget.image, **bbox} for bbox in widget.bboxes)
```
I would strongly prefer to leave this sort of data massage to the user =).

**Comment by MarcSkovMadsen** [comment]
Thx. I misunderstood how the widget worked. I did not realise at first that the `bboxes` was reset on skip. I thought it keept track of `bboxes` across images.

**Comment by gereleth** [comment]
Might there still be some misunderstanding left?.. The widget doesn't dictate what should happen either on skip or on submit. Without user-supplied callbacks nothing at all will happen. So whether or not the bboxes are reset on skip is completely up to the user.

But it's true that the widget is not supposed to store annotation data for multiple images - it just shows the current image and its corresponding bounding boxes.
