### ISSUE TITLE
Make it possible to submit programmatically

### ISSUE THREAD

**Issue by MarcSkovMadsen** [gereleth/jupyter-bbox-widget#28]
If you want to use the widget with a data app framework like [Panel](https://panel.holoviz.org/reference/index.html), Shiny Py or Solara you want to be in the control of the location and style of buttons.

Please make it possible to hide the built in buttons (already possible) and trigger submit via code. Then I as a data app developer can trigger submit from one of my own buttons or triggered by other events.

**Comment by gereleth** [comment]
I don't really understand this request. The widget's submit does nothing by itself, only what you supply in the callback. If you have your own submit button then the callback can just go live there instead, can't it? =)

**Comment by MarcSkovMadsen** [comment]
Agree. You may close this one.
