### ISSUE TITLE
Make it possible to provide callbacks in init

### ISSUE THREAD

**Issue by MarcSkovMadsen** [gereleth/jupyter-bbox-widget#29]
Currently you cannot set the `skip_callback` and `submit_callback` in the `__init__`.

![image](https://github.com/user-attachments/assets/67e08cda-9ff9-4cc0-8daf-2f780a90dc08)

You will have to set them manually after initialization. And if you use `@skip_callback` function  define the functions after you've defined the widget. 

That makes the code longer than it has to be. And you don't give me freedom to organize my code. For example I would like to be able to define the callbacks in an external, reusable module and just provide them on initialization.

**Comment by gereleth** [comment]
I guess I was mimicking regular ipywidgets buttons where you first create a `Button` and then assign a callback with `button.on_click(handle_click)`. I don't know if there's a specific reason they do it this way (maybe it's to support multiple callbacks on the same button?..)

Just to be sure I understand - we're discussing the difference between these options, right? They even have the same number of lines so I'm not sure what's to be gained =).

```python
# current
widget = BBoxWidget(
    image="...",
    classes=["..."],
)
widget.on_submit(handle_submit)
widget.on_skip(handle_skip)
```

and 

```python
# proposed
widget = BBoxWidget(
    image="...",
    classes=["..."],
    submit_callback=handle_submit,
    skip_callback=handle_skip,
)
```

**Comment by MarcSkovMadsen** [comment]
I can see the difference is minimal. It's probably subjective, but I believe the first one is more readable.

**Comment by MarcSkovMadsen** [comment]
Thanks for I'm creating the two examples. I'm used to version 2. It feels more right. But I think there are valid arguments for both versions.
