### ISSUE TITLE
Please allow to remove submit and skip buttons at least in view_only mode

### ISSUE THREAD

**Issue by ffeldhaus** [gereleth/jupyter-bbox-widget#3]
In the view_only mode the submit and skip buttons are not necessary and in some cases more flexibility is required how submit and skip buttons are being displayed. Please allow to remove submit and skip buttons from the output.

**Comment by gereleth** [comment]
In v0.3.2 you can hide the buttons with `widget.hide_buttons = True`. 
I think this is a separate concern from view_only mode so these options can be used independently.
