### ISSUE TITLE
Draw custom masks on the current image

### ISSUE THREAD

**Issue by nicolas-busca** [gereleth/jupyter-bbox-widget#32]
Hi there!
I'd like to run [S.A.M.](https://github.com/facebookresearch/segment-anything) after drawing a bounding box and draw the predicted segmentation mask on the image. I am able to run the model by capturing the change in the bounding box, but how can I overlay it on the image?

**Comment by gereleth** [comment]
Hi!

Suppose you created a widget like this:

```python
from jupyter_bbox_widget import BBoxWidget
widget = BBoxWidget(
    image='fruit/fruit.jpg',
    classes=['apple', 'orange', 'pear'],
)
widget
```

And then you got a segmentation mask. You can probably draw this mask on the image in python, right? Then one option is to save the masked image into a temporary file and do something like `widget.image = 'masked.jpg'`.
Or you can save the masked image in-memory and give that to the widget like here:

```python
from PIL import Image, ImageDraw
from io import BytesIO
# draw the mask on the image - here just a rectangle for testing
masked_img = Image.open('fruit/fruit.jpg')
ImageDraw.Draw(masked_img).rectangle(((50,50), (200,200)), fill ="#800080") 
# save image file into an in-memory buffer and give that to the widget
bytes_io = BytesIO()
masked_img.save(bytes_io, format='jpeg', quality=90)
widget.image_bytes = bytes_io.getvalue()
```

**Comment by nicolas-busca** [comment]
Amazing!
