### ISSUE TITLE
Make selected_index the value of the widget

### ISSUE THREAD

**Issue by ffeldhaus** [gereleth/jupyter-bbox-widget#4]
It would be useful in several cases if the widget would return a value which [ipywidgets seem to have in common](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Basics.html#Widget-properties). Using selected_index is a good choice for value as most operations are dealing with the selected bbox.

**Comment by gereleth** [comment]
Hmm, do you want `selected_index` to be called `value`?

The data model here is a bit more complex than that of a simple `IntSlider`. In my opinion `bboxes` is the value of this widget, not `selected_index`. That's why I prefer descriptive names over a generic `value`.

**Comment by ffeldhaus** [comment]
You are right, it could also be `bboxes`. Now that I understand how to use `observe` with the widget parameters, I think `value` is not necessary.
