### ISSUE TITLE
using "C assign selected class label" shortcut doesn't update the bounding boxes

### ISSUE THREAD

**Issue by alexheat** [gereleth/jupyter-bbox-widget#5]
Hi. I love your tool. I think I found a small bug. 

If I use the "C" shortcut the display value of the widget changes but when I get the value of the .bboxes it doesn't reflect the new class value. I have to move one of the boxes in order for the class name to be reflected. 

To repro in your sample notebook. 
- Draw a box with label "apple"
- Select the box. Select class name "pear" in the list of classes
- Press "C" class changes to Pear
- Check value of widget.bboxes, class name is apple
- Move the box
- Check the value of widget.bboxes, class name is pear

**Comment by gereleth** [comment]
Hi, thanks for reporting!

This should be fixed in v.0.3.3.

**Comment by alexheat** [comment]
Wonderful. Thank you!
